### ISSUE TITLE
Long-term Idea: LaTeX Integration

### ISSUE THREAD

**Issue by donald-pinckney** [chriseidhof/LiterateSwiftGUI#3]
I have no idea how this could work, but one super useful tool for writing in the sciences is LaTeX.  Although the intent of this project might be focused on writing playgrounds / books about Swift, it seems reasonable to also write a book / playground about some STEM field, and involve Swift (rather than something like SciPy for example).  Recently I played around with creating a Playground concerning Schrödinger's Equation, and actually embedded rendered LaTeX PDFs into the playground (they work just like embedding images, in the Resources folder). To give an idea, here is a screen cap of it:
<img width="1440" alt="latex" src="https://cloud.githubusercontent.com/assets/4752260/8491366/09b56aa6-20ec-11e5-851a-92ca86252d91.png">
The math looks beautifully rendered, and flows pretty well with the rest of the text.
It really was a pain though to render the LaTeX content separately, especially for editing it later.  Perhaps literate swift could somehow assist with writing LaTeX code inline along with the Markdown, and then automatically creating the PDFs / Playground.

**Comment by chriseidhof** [comment]
This should be very doable as a standalone tool. Maybe in combination with [pandoc](http://johnmacfarlane.net/pandoc/) ?

**Comment by donald-pinckney** [comment]
Pandoc could certainly be helpful for this, and implementing it as a standalone tool makes sense.  This summer I am interning at Apple, and thus shouldn't commit code to an open source Swift related project.  Once fall quarter starts I might have time to help with this though.

**Comment by chriseidhof** [comment]
Cool. Closing this for now, once the tool is there we can see if it would fit in (but probably a library would be better).
