### ISSUE TITLE
Need to install cmake & Xcode 7 / Swift 2 (add to README.md)

### ISSUE THREAD

**Issue by dfreniche** [chriseidhof/LiterateSwiftGUI#4]
While was trying to install LiterateSwiftGUI a minor problem occurred:

```
Installing cmark (0.21.0)
[!] /bin/bash -c
set -e
echo `pwd`
sed -i '' 's/include <\(cmark.*\)>/include "\1"/' src/cmark.h
mkdir -p build; cd build && cmake -G Xcode ..

/Users/dfreniche/Library/Caches/CocoaPods/Pods/Release/cmark/0.21.0-0868a
/bin/bash: line 4: cmake: command not found
```

Obvious enough, I didn't have cmake installed. Solved using Homebrew:

```
brew install cmake
```

Also, if you try to compile using Xcode 6 you'll get lots of errors, because Captain Obvious will tell you this is all Swift 2 😉

**Comment by chriseidhof** [comment]
Hm, do you know if it's possible to specify cmake as a CocoaPods dependency? That would help a lot.

**Comment by dfreniche** [comment]
Don't think so, although I'm no expert in Ruby / CocoaPods. But just a simple two-liner in BASH should suffice (adding that to the README)

**EDIT**: Just seen the README file has been update. Awesome!
